server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.193.94:3306/app?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: wzp123
    flag:
#    hikari:
#      maximum-pool-size: 50
#      minimum-idle: 10

  application:
    name: "xiaopeng_server"
  # Redis 配置
  redis:
    # Redis 服务器地址
    host: 47.106.193.94
    # 连接端口号
    port: 6379
    password: root123
    # 数据库索引（0 - 15）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10000
  rabbitmq:
    password: admin
    username: admin
    port: 5672
    addresses: 47.106.193.94
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    listener:
      simple:
        #指定最小的消费者数量.
        concurrency: 2
        #指定最大的消费者数量.
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
#        acknowledge-mode: MANUAL
    #支持消息的确认与返回
    template:
      mandatory: true
## mybatis
##实现mapper接口配置见mapper和接口的绑定路径
##将带有下划线的表字段映射为驼峰格式的实体类属性
#mybatis:
#  mapper-locations: classpath*:/mybatis/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
wechatConfig:
  appId: 1
  appSecret: 2
