server:
  port: 8080
  servlet:
    context-path: /aiops
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.221.225.23:3306/xiaopeng_server?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
#    hikari:
#      maximum-pool-size: 50
#      minimum-idle: 10

  application:
    name: "xiaopeng_server"
# mybatis
mybatis:
  mapper-locations: classpath*:/mybatis/**/*Mapper.xml
  configuration:
