server:
  port: 8080
  servlet:
    context-path: /api
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
spring:
  mvc:
    static-path-pattern=/**:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.193.94:3306/app?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: wzp123
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 10
      maxWait: 60000     #获取连接时最大等待时间，单位毫秒
      timeBetweenEvictionRunsMillis: 60000     #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      testWhileIdle: true       #建议配置为true，不影响性能，并且保证安全性。如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testOnBorrow: false       #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false       #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭


  application:
    name: "xiaopeng_server"
  # Redis 配置
  redis:
    # Redis 服务器地址
    host: 47.106.193.94
    # 连接端口号
    port: 6379
    password: wzp@java
    # 数据库索引（0 - 15）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10000
  rabbitmq:
    password: admin
    username: admin
    port: 5672
    addresses: 47.106.193.94
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    listener:
      simple:
        #指定最小的消费者数量.
        concurrency: 2
        #指定最大的消费者数量.
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
#        acknowledge-mode: MANUAL
    #支持消息的确认与返回
    template:
      mandatory: true

## mybatis
##实现mapper接口配置见mapper和接口的绑定路径
##将带有下划线的表字段映射为驼峰格式的实体类属性
#mybatis:
#  mapper-locations: classpath*:/mybatis/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
wechatConfig:
  appId: 1
  appSecret: 2,3,4